name: Dobby is Free

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  build:
    name: Dobby Checks the Build
    runs-on: ubuntu-latest

    steps:
      - name: Dobby Picks Up the Code
        uses: actions/checkout@v4

      - name: Dobby Prepares Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm

      - name: Dobby Installs Dependencies
        run: npm ci

      - name: Dobby Prepares Environment Variables
        run: |
          echo "VITE_TEST_DATA=${{ secrets.VITE_TEST_DATA }}" >> $GITHUB_ENV

      - name: Dobby Checks the Frontend Build
        run: npm run build

  deploy:
    name: Dobby Deploys to S3
    runs-on: ubuntu-latest
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Dobby Picks Up the Code
        uses: actions/checkout@v4

      - name: Dobby Prepares Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm

      - name: Dobby Installs Dependencies
        run: npm ci

      - name: Dobby Prepares Environment Variables
        run: |
          echo "VITE_TEST_DATA=${{ secrets.VITE_TEST_DATA }}" >> $GITHUB_ENV

      - name: Dobby Packs the Frontend
        run: npm run build

      - name: Dobby Sends Files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
